; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat May 16 2020 23:03:57 GMT+0800 (China Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


