; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Feb 05 2020 20:36:07 GMT+0800 (China Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


