; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Feb 05 2020 20:36:07 GMT+0800 (China Standard Time)

