; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat May 16 2020 23:03:57 GMT+0800 (China Standard Time)

