; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Sat May 16 2020 23:03:57 GMT+0800 (China Standard Time)
; Wait for set temperatures to be reached
M116 P0

