; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Wed Feb 05 2020 20:36:07 GMT+0800 (China Standard Time)
; Wait for set temperatures to be reached
M116 P0

